# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
development:
  adapter: sqlite3
  database: db/development.sqlite3
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  encoding: unicode
  database: abeira_test
  pool: 5
  username: postgres
  password: hahaha

production:
  adapter: postgresql
  encoding: unicode
  database: abeira_production
  pool: 5
  username: abeira
  password: 